// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfqO3E_FnP8si64cJdd2SV0f4Ro165OiE',
    appId: '1:825700866397:web:acb1c46cd0bf3ba03d70b4',
    messagingSenderId: '825700866397',
    projectId: 'elms-d2336',
    authDomain: 'elms-d2336.firebaseapp.com',
    storageBucket: 'elms-d2336.firebasestorage.app',
    measurementId: 'G-2SS96JK9MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD61inhAja6knwwFNNJd2mavFK9RTrkAvA',
    appId: '1:825700866397:android:c9e56b407c7759fa3d70b4',
    messagingSenderId: '825700866397',
    projectId: 'elms-d2336',
    storageBucket: 'elms-d2336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Yo2P1ikm3gax5L290dl3DwHCLMd5dxc',
    appId: '1:825700866397:ios:fe65aac67b80b69c3d70b4',
    messagingSenderId: '825700866397',
    projectId: 'elms-d2336',
    storageBucket: 'elms-d2336.firebasestorage.app',
    iosBundleId: 'com.example.chatsys',
  );
}
